import PrimaryLayout from '@/components/layouts/primary/PrimaryLayout';
import SidebarLayout from '@/components/layouts/sidebar/SidebarLayout';
import { Inter } from '@next/font/google';
import Head from 'next/head';
import { NextPageWithLayout } from './page';

const inter = Inter({ subsets: ['latin'] });

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-r from-red-400 to-blue-500 text-xl">
        Home Page again
      </main>
    </>
  );
};

export default Home;

Home.getLayout = (page: React.ReactElement) => {
  return (
    <PrimaryLayout>
      <SidebarLayout />
      {page}
    </PrimaryLayout>
  );
};
